wandb_version: 1

dataset:
  desc: null
  value:
    perc_edges: 10
model:
  desc: null
  value:
    K_neigs: 2
    dropout: 0.25
    hidden_size: 8
    num_layers: 3
training:
  desc: null
  value:
    l2: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692789743.059994
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      - 37
      4: 3.11.2
      5: 0.15.0
      8:
      - 1
      - 5
