wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692788725.209742
    t:
      1:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 50
      - 53
      - 55
      - 77
      3:
      - 23
      4: 3.11.2
      5: 0.15.0
      8:
      - 5
