defaults: 
  - dataset: fc_large
  - model: dwhgn   # dwattnhgn,attnhgn,dwhgn,hypergraphgcn
  - optimizer: adam
  - training: train


dataset:
  node: fc

model: 
  K_neigs: 40
  num_layers: 2
  hidden_size: 64  # 8, 16, 32, 64, 128
  dropout: 0.5     # 0.25
  heads: 1
  readout: linear #linear, set_transformer, janossy
  attention_mode: edge
  num_perm: 25

log_path: result

repeat_time: 4

# total_steps: 100 # remove this later

device: cuda:0

# wandb:
is_wandb: True
# doing_sweep: True
project: wacv24
entity: mehular0ra
# sweep_id: asd-graph/asd-graph/r49h4avh



hydra:
  job_logging:
    root:
      handlers: [console, file]
      propagate: true
    formatters:
      precise:
        format: '[%(asctime)s][%(filename)s][L%(lineno)d][%(levelname)s]%(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: precise
        filename: ./output.log

