defaults: 
  - dataset: fc_large
  - model: signedgcn
  - optimizer: adam
  - training: train


dataset:
  node: fc


log_path: result

repeat_time: 2

# total_steps: 100 # remove this later

device: cuda:0

# wandb:
is_wandb: False
project: asd-graph



hydra:
  job_logging:
    root:
      handlers: [console, file]
      propagate: true
    formatters:
      precise:
        format: '[%(asctime)s][%(filename)s][L%(lineno)d][%(levelname)s]%(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: precise
        filename: ./output.log

