defaults: 
  - dataset: fc_large
  - model: hypergraphgcn
  - optimizer: adam
  - training: train


dataset:
  node: fc

models: 
  K_neigs: 4
  num_layers: 2
  hidden_size: 64  # 8, 16, 32, 64, 128
  dropout: 0.5     # 0.25


log_path: result

repeat_time: 1

# total_steps: 100 # remove this later

device: cuda:0

# wandb:
is_wandb: False
# doing_sweep: True
project: asd-graph
entity: mehular0ra
# sweep_id: asd-graph/asd-graph/r49h4avh



hydra:
  job_logging:
    root:
      handlers: [console, file]
      propagate: true
    formatters:
      precise:
        format: '[%(asctime)s][%(filename)s][L%(lineno)d][%(levelname)s]%(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: precise
        filename: ./output.log

