name: fc_small
batch_size: 32
test_batch_size: 1
val_batch_size: 1
train_set: 0.8
val_set: 0.2
fc_path: /mnt/ssd1/mehul_data/research/fc_small_data.npy
drop_last: True
stratified: True

node_sz: 400
node_feature_sz: 400
num_classes: 2
